<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headLink()->appendStylesheet('/style/base.css') ?>
  <title>Zend Base</title>
</head>
<body>
<?php echo $this->partial('debug.phtml'); ?>
<?php echo $this->partial('account-header.phtml'); ?>
<?php echo $this->partial('flash.phtml', array('messages'=>$this->flash())); ?>

<?php echo $this->layout()->content ?>
</body>
</html>