<ul>
	<li>
		<a href="<?php echo $this->url(array(
		          'controller' => 'admin',
		          'action'     => 'list-users'
		      )) ?>">users</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array(
		          'controller' => 'admin',
		          'action'     => 'list-roles'
		      )) ?>">roles</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array(
		          'controller' => 'admin',
		          'action'     => 'list-resources'
		      )) ?>">resources</a>
	</li>
</ul>