<h2>Users</h2>
<form method="post" action="<?php echo $this->url(array(
          'controller' => 'admin',
          'action'     => 'edit-user-roles'
      )) ?>">
      
<h3>Edit roles for selected users</h3>
<table>
    <tr>
    	<th></th>
	    <th>id</th>
	    <th>username</th>
	    <th>roles</th>
	</tr>	
    <?php foreach ($this->users as $user): ?>
    <tr>
    	<td><INPUT TYPE="checkbox" NAME="users[<?php echo $user->id ?>]" VALUE=""/></td>
	    <td><?php echo $user->id ?></td>
	    <td><?php echo $this->escape($user->username) ?></td>
	    <td>
	    	<?php if ($this->rolesByUser[$user->id]):?>
	    		<?php echo implode(",",$this->rolesByUser[$user->id]) ?>
	    	<?php endif ?>
	    </td>
	</tr>	
    <?php endforeach; ?>
</table>
<select id="action" name="action">
	<option value="grant">grant</option>
	<option value="revoke">revoke</option>
</select>
<label for="role">role</label>
<select id="role" name="role">
<?php foreach ($this->allRoles as $role): ?>
	<option value="<?php echo $role->id ?>"><?php echo $role->name ?></option>
<?php endforeach; ?>
</select>
<input value="update users" type="submit"/>
</form>
<h3>Create new user</h3>

<?php
$this->newUserForm->setAction($this->url(array(
          'controller' => 'admin',
          'action'     => 'create-user'
      )));
echo $this->newUserForm;
?>